import {
  Backpack,
  BedDouble,
  Briefcase,
  Building2,
  CalendarDays,
  Car,
  CarTaxiFront,
  Compass,
  CreditCard,
  Eraser,
  FerrisWheel,
  Flower2,
  Footprints,
  Globe,
  Heart,
  Hotel,
  Inbox,
  Landmark,
  Luggage,
  MapPin,
  Mountain,
  MountainSnow,
  Music,
  Pencil,
  Phone,
  Plane,
  PlaneTakeoff,
  Save,
  Search,
  Settings,
  Ship,
  ShoppingBag,
  Siren,
  Snowflake,
  Sparkles,
  Stethoscope,
  StickyNote,
  Sun,
  Tent,
  Ticket,
  TrainFront,
  TramFront,
  Trash2,
  TreePalm,
  Utensils,
  Wallet,
  Waves,
  type LucideIcon,
} from "lucide-react";

/** Icon id → glyph. Trips and destinations store the id. */
export const ICON_MAP: Record<string, LucideIcon> = {
  backpack: Backpack,
  beach: TreePalm,
  bed: BedDouble,
  broom: Eraser,
  calendar: CalendarDays,
  camping: Tent,
  city: Building2,
  compass: Compass,
  creditcard: CreditCard,
  cruise: Ship,
  flight: PlaneTakeoff,
  floppy: Save,
  flower: Flower2,
  food: Utensils,
  gear: Settings,
  globe: Globe,
  hiking: Footprints,
  hotel: Hotel,
  inbox: Inbox,
  landmark: Landmark,
  luggage: Luggage,
  memo: StickyNote,
  moneybag: Wallet,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  music: Music,
  pencil: Pencil,
  phone: Phone,
  pin: MapPin,
  plane: Plane,
  roadtrip: Car,
  romance: Heart,
  search: Search,
  shopping: ShoppingBag,
  siren: Siren,
  snowflake: Snowflake,
  sparkles: Sparkles,
  medical: Stethoscope,
  sun: Sun,
  taxi: CarTaxiFront,
  themepark: FerrisWheel,
  ticket: Ticket,
  train: TrainFront,
  tram: TramFront,
  trash: Trash2,
  waves: Waves,
  work: Briefcase,
};

export function getIcon(id: string): LucideIcon {
  return ICON_MAP[id] ?? Globe;
}

export const TRIP_ICON_CHOICES: { id: string; label: string }[] = [
  { id: "globe", label: "Globe" },
  { id: "beach", label: "Beach" },
  { id: "mountain", label: "Mountains" },
  { id: "city", label: "City" },
  { id: "backpack", label: "Backpacking" },
  { id: "flight", label: "Flight" },
  { id: "roadtrip", label: "Road trip" },
  { id: "cruise", label: "Cruise" },
  { id: "camping", label: "Camping" },
  { id: "themepark", label: "Theme park" },
  { id: "work", label: "Work" },
  { id: "romance", label: "Romance" },
];

/** Maps trip icons stored as emoji by earlier builds onto icon ids. */
export const LEGACY_EMOJI_ICONS: Record<string, string> = {
  "🌍": "globe",
  "🏝️": "beach",
  "⛰️": "mountain",
  "🏔️": "mountain-snow",
  "🏙️": "city",
  "🎒": "backpack",
  "🛫": "flight",
  "🚗": "roadtrip",
  "🛳️": "cruise",
  "🏕️": "camping",
  "🎢": "themepark",
  "💼": "work",
  "❤️": "romance",
  "🌊": "waves",
};
